### ISSUE TITLE
mapa_mental_wed3.0_charly

### ISSUE THREAD

**Issue by Sandoval6** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Sandoval6#2]
[wed 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-Sandoval6/files/14728337/wed.3.0.pdf)

**Comment by Edwin14459** [comment]
**Calificación en base a la rúbrica:**

Identificación del tema principal: 4 puntos
Contenidos / Conceptos: 4 puntos.
Organización y estructura: 4 puntos.
Formato: 4 puntos
Difusión: 4 puntos. 

**Calificación total: _20/20_**

**Comment by josealfredo79** [comment]
bien hecho y revisado...
